/**
 * Dumps all CMS content from a Supabase project into supabase/seed.sql.
 *
 * The output is a plain SQL file that recreates every content row exactly,
 * so a fresh project can be brought up with:
 *
 *   1. supabase/migrations/00000000000000_baseline.sql   (schema)
 *   2. supabase/seed.sql                                 (content)
 *
 * Rows are written as json_populate_recordset() inserts rather than column
 * lists, so adding a column to a table doesn't silently break the seed — the
 * new column simply comes through with whatever the JSON carries (or its
 * default, when the key is absent).
 *
 * Personal data is NEVER dumped. contact_requests, job_applications,
 * contact_messages and profiles are excluded on purpose: they hold names,
 * phone numbers, CVs and grievances belonging to real people, and they have
 * no business travelling with the codebase. See EXCLUDED below.
 *
 * Usage:
 *   node scripts/dump-seed.mjs                  # uses .env
 *   node scripts/dump-seed.mjs --out other.sql
 *
 * Requires SUPABASE_SERVICE_ROLE_KEY, because the point is to capture
 * unpublished drafts too — the anon key would silently skip them.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Minimal .env reader — avoids adding dotenv as a dependency for one script. */
function loadEnv() {
  try {
    for (const line of readFileSync(join(root, ".env"), "utf8").split("\n")) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m && !process.env[m[1]]) process.env[m[1]] = m[2].trim();
    }
  } catch {
    /* no .env — rely on the ambient environment */
  }
}
loadEnv();

const URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!URL || !KEY) {
  console.error(
    "Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.\n" +
      "Set them in my-app/.env or in the environment before running this.",
  );
  process.exit(1);
}

/**
 * Dump order matters: jobs before anything that references it. Everything
 * here is content the site renders — safe to ship, safe to share.
 */
const TABLES = [
  "site_settings",
  "page_content",
  "hero_slides",
  "focus_areas",
  "program_panels",
  "programs",
  "news",
  "gallery_items",
  "reports",
  "policies",
  "kpis",
  "team_members",
  "board_committees",
  "org_levels",
  "mosques",
  "jobs",
];

/** Personal data. Never dumped, never committed. */
const EXCLUDED = ["profiles", "contact_messages", "contact_requests", "job_applications"];

/**
 * Reads a whole table over PostgREST.
 *
 * Deliberately plain fetch rather than @supabase/supabase-js: the SDK pulls in
 * realtime-js, which throws on Node < 22 for want of a native WebSocket. This
 * script only needs GET, so the dependency buys nothing and costs portability.
 */
async function selectAll(table) {
  const res = await fetch(`${URL}/rest/v1/${table}?select=*`, {
    headers: { apikey: KEY, Authorization: `Bearer ${KEY}` },
  });
  if (!res.ok) return { error: `${res.status} ${await res.text()}` };
  return { data: await res.json() };
}

/** Postgres dollar-quoting so Arabic content and embedded quotes need no escaping. */
function dollarQuote(text) {
  let tag = "$seed$";
  let n = 0;
  while (text.includes(tag)) tag = `$seed${++n}$`;
  return `${tag}${text}${tag}`;
}

const outArg = process.argv.indexOf("--out");
const outPath = outArg !== -1 ? process.argv[outArg + 1] : join(root, "supabase", "seed.sql");

const parts = [
  `-- ============================================================================`,
  `-- seed.sql — CMS content for the Almajdouie Foundation site.`,
  `--`,
  `-- GENERATED by scripts/dump-seed.mjs — do not hand-edit. Regenerate with:`,
  `--   node scripts/dump-seed.mjs`,
  `--`,
  `-- Run AFTER migrations/00000000000000_baseline.sql. Safe to re-run: every`,
  `-- statement is ON CONFLICT DO NOTHING, so it tops up a partial database`,
  `-- without overwriting anything an editor has since changed.`,
  `--`,
  `-- Contains NO personal data — ${EXCLUDED.join(", ")} are excluded by design.`,
  `--`,
  `-- Source: ${URL}`,
  `-- Dumped: ${new Date().toISOString()}`,
  `-- ============================================================================`,
  ``,
];

let grandTotal = 0;

for (const table of TABLES) {
  const { data, error } = await selectAll(table);

  if (error) {
    console.error(`  ✗ ${table}: ${error}`);
    process.exitCode = 1;
    continue;
  }

  const rows = data ?? [];
  grandTotal += rows.length;
  console.log(`  ✓ ${table.padEnd(18)} ${String(rows.length).padStart(3)} rows`);

  parts.push(`-- ${table} — ${rows.length} row${rows.length === 1 ? "" : "s"}`);

  if (rows.length === 0) {
    parts.push(`-- (empty at dump time)`, ``);
    continue;
  }

  // json_populate_recordset maps by key name, so a column added later still
  // works: absent keys fall back to the column default.
  parts.push(
    `insert into public.${table}`,
    `select * from json_populate_recordset(null::public.${table},`,
    dollarQuote(JSON.stringify(rows, null, 2)),
    `::json)`,
    `on conflict do nothing;`,
    ``,
  );
}

parts.push(
  `-- ── Sequences ───────────────────────────────────────────────────────────────`,
  `-- The ticket/application counters are not seeded (their tables hold personal`,
  `-- data and are excluded), so a fresh database starts both at 1: the first`,
  `-- complaint becomes REQ-<year>-000001 and the first application APP-<year>-000001.`,
  ``,
  `-- ── After running this file ─────────────────────────────────────────────────`,
  `-- 1. Create your first auth user in the Supabase dashboard.`,
  `-- 2. Promote them:`,
  `--      update public.profiles set role = 'super_admin' where email = '<you>';`,
  `-- 3. Re-upload the images referenced by these rows, or point them at your own`,
  `--    Storage bucket — see supabase/SETUP.md, step 6.`,
  ``,
);

writeFileSync(outPath, parts.join("\n"), "utf8");
console.log(`\n  ${grandTotal} rows → ${outPath}`);
